services:
  # Load Balancer - Routes traffic to API replicas
  nginx:
    image: nginx:alpine
    container_name: gopay-nginx
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - gopay

  # API Service (will be scaled manually)
  api:
    build:
      context: .
      dockerfile: dockerfile
    image: gopay:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "${APP_PORT}"
    env_file:
      - .env
    networks:
      - gopay
    depends_on:
      - "opensearch"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Search Engine
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: ${APP_NAME}-opensearch
    restart: always
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "cluster.name=gopay-cluster"
      - "node.name=gopay-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - gopay
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  opensearch_data:
    driver: local

networks:
  gopay:
    name: gopay
    driver: bridge
