apiVersion: v1
kind: Namespace
metadata:
  name: gopay
  labels:
    name: gopay
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gopay-config
  namespace: gopay
data:
  APP_PORT: "9999"
  APP_NAME: "gopay"
  ENVIRONMENT: "production"
  OPENSEARCH_URL: "http://opensearch:9200"
  ENABLE_OPENSEARCH_LOGGING: "true"
  LOGGING_LEVEL: "info"
  LOG_RETENTION_DAYS: "30"
---
apiVersion: v1
kind: Secret
metadata:
  name: gopay-secrets
  namespace: gopay
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  API_KEY: eW91cl9zdXBlcl9zZWNyZXRfYXBpX2tleQ== # your_super_secret_api_key
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleQ== # your_jwt_secret_key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gopay-data
  namespace: gopay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopay-api
  namespace: gopay
  labels:
    app: gopay-api
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: gopay-api
  template:
    metadata:
      labels:
        app: gopay-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: gopay
        image: ghcr.io/mstgnz/gopay:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: http
        - containerPort: 8080
          name: metrics
        env:
        - name: APP_URL
          value: "https://gopay.yourdomain.com"
        envFrom:
        - configMapRef:
            name: gopay-config
        - secretRef:
            name: gopay-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gopay-data
      securityContext:
        fsGroup: 65534
      serviceAccountName: gopay-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gopay-api
  namespace: gopay
---
apiVersion: v1
kind: Service
metadata:
  name: gopay-api-service
  namespace: gopay
  labels:
    app: gopay-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9999
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: gopay-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gopay-ingress
  namespace: gopay
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
  - hosts:
    - gopay.yourdomain.com
    secretName: gopay-tls
  rules:
  - host: gopay.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gopay-api-service
            port:
              number: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gopay-api-pdb
  namespace: gopay
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: gopay-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gopay-api-hpa
  namespace: gopay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gopay-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max 